# Generated by Django 5.0.4 on 2024-04-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('https', 'HTTP(s)'), ('ping', 'ICMP'), ('host', 'Port')], max_length=15)),
                ('url', models.URLField()),
                ('status', models.CharField(blank=True, max_length=100)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('response_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
