# Generated by Django 5.0.4 on 2024-04-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ping_Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='protocol',
            field=models.CharField(choices=[('https', 'https'), ('ping', 'ICMP'), ('host', 'Port')], max_length=15),
        ),
    ]
