# Generated by Django 5.0.4 on 2024-04-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ping_Service', '0002_alter_ping_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ping',
            name='url',
            field=models.TextField(),
        ),
    ]
