# Generated by Django 5.0.4 on 2024-05-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ping_Service', '0003_alter_ping_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ping',
        ),
    ]
